name: Create production promotion pull request
on:
  push:
    branches:
      - DEV_MAIN
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ref: DEV_MAIN
      - name: Reset QA branch
        run: |
          git fetch origin DEV_MAIN:TC_QA
          git reset --hard TC_QA
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: TC_QA
